//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.26 at 03:58:35 PM ALMT 
//


package com.hibernate.tutorial.app.xml.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZAP" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="N_ZAP" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="IDDOCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LPUKOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DOKT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="SERTIF" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="N_SERT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="REG_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DATE_END" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PRVS" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zap"
})
@XmlRootElement(name = "packet")
public class Packet {

    @XmlElement(name = "ZAP")
    private List<Packet.ZAP> zap;

    /**
     * Gets the value of the zap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Packet.ZAP }
     * 
     * 
     */
    public List<Packet.ZAP> getZAP() {
        if (getZap() == null) {
            setZap(new ArrayList<Packet.ZAP>());
        }
        return this.getZap();
    }

    /**
     * @return the zap
     */
    public List<Packet.ZAP> getZap() {
        return zap;
    }

    /**
     * @param zap the zap to set
     */
    public void setZap(List<Packet.ZAP> zap) {
        this.zap = zap;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="N_ZAP" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="IDDOCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LPUKOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FAM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DOKT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="SERTIF" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="N_SERT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="REG_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DATE_END" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PRVS" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nzap",
        "iddoct",
        "lpukod",
        "fam",
        "im",
        "ot",
        "dokt",
        "sertif"
    })
    public static class ZAP {

        @XmlElement(name = "N_ZAP")
        protected short nzap;
        @XmlElement(name = "IDDOCT")
        protected int iddoct;
        @XmlElement(name = "LPUKOD", required = true)
        protected String lpukod;
        @XmlElement(name = "FAM", required = true)
        protected String fam;
        @XmlElement(name = "IM", required = true)
        protected String im;
        @XmlElement(name = "OT", required = true)
        protected String ot;
        @XmlElement(name = "DOKT")
        protected byte dokt;
        @XmlElement(name = "SERTIF")
        private List<Packet.ZAP.SERTIF> sertif;

        /**
         * Gets the value of the nzap property.
         * 
         */
        public short getNZAP() {
            return nzap;
        }

        /**
         * Sets the value of the nzap property.
         * 
         */
        public void setNZAP(short value) {
            this.nzap = value;
        }

        /**
         * Gets the value of the iddoct property.
         * 
         */
        public int getIDDOCT() {
            return iddoct;
        }

        /**
         * Sets the value of the iddoct property.
         * 
         */
        public void setIDDOCT(int value) {
            this.iddoct = value;
        }

        /**
         * Gets the value of the lpukod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLPUKOD() {
            return lpukod;
        }

        /**
         * Sets the value of the lpukod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLPUKOD(String value) {
            this.lpukod = value;
        }

        /**
         * Gets the value of the fam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFAM() {
            return fam;
        }

        /**
         * Sets the value of the fam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFAM(String value) {
            this.fam = value;
        }

        /**
         * Gets the value of the im property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIM() {
            return im;
        }

        /**
         * Sets the value of the im property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIM(String value) {
            this.im = value;
        }

        /**
         * Gets the value of the ot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOT() {
            return ot;
        }

        /**
         * Sets the value of the ot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOT(String value) {
            this.ot = value;
        }

        /**
         * Gets the value of the dokt property.
         * 
         */
        public byte getDOKT() {
            return dokt;
        }

        /**
         * Sets the value of the dokt property.
         * 
         */
        public void setDOKT(byte value) {
            this.dokt = value;
        }

        /**
         * Gets the value of the sertif property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sertif property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSERTIF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Packet.ZAP.SERTIF }
         * 
         * 
         */
        public List<Packet.ZAP.SERTIF> getSERTIF() {
            if (getSertif() == null) {
                setSertif(new ArrayList<Packet.ZAP.SERTIF>());
            }
            return this.getSertif();
        }

        /**
         * @return the sertif
         */
        public List<Packet.ZAP.SERTIF> getSertif() {
            return sertif;
        }

        /**
         * @param sertif the sertif to set
         */
        public void setSertif(List<Packet.ZAP.SERTIF> sertif) {
            this.sertif = sertif;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="N_SERT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="REG_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DATE_END" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PRVS" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nsert",
            "regnum",
            "dateend",
            "prvs"
        })
        public static class SERTIF {

            @XmlElement(name = "N_SERT", required = true)
            protected String nsert;
            @XmlElement(name = "REG_NUM", required = true)
            protected String regnum;
            @XmlElement(name = "DATE_END", required = true)
            protected String dateend;
            @XmlElement(name = "PRVS")
            protected short prvs;

            /**
             * Gets the value of the nsert property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNSERT() {
                return nsert;
            }

            /**
             * Sets the value of the nsert property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNSERT(String value) {
                this.nsert = value;
            }

            /**
             * Gets the value of the regnum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREGNUM() {
                return regnum;
            }

            /**
             * Sets the value of the regnum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREGNUM(String value) {
                this.regnum = value;
            }

            /**
             * Gets the value of the dateend property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDATEEND() {
                return dateend;
            }

            /**
             * Sets the value of the dateend property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDATEEND(String value) {
                this.dateend = value;
            }

            /**
             * Gets the value of the prvs property.
             * 
             */
            public short getPRVS() {
                return prvs;
            }

            /**
             * Sets the value of the prvs property.
             * 
             */
            public void setPRVS(short value) {
                this.prvs = value;
            }

        }

    }

}
